Don't name variable varlena, avoids name conflict on PG19
In file included from /usr/include/postgresql/19/server/access/skey.h:19,
                 from /usr/include/postgresql/19/server/access/heapam.h:21,
                 from src/native.c:23:
/home/runner/work/pg_chdb/pg_chdb/vendor/pg-clickhouse-c/pg-clickhouse-decode.h: In function ‘pgch_value_to_cstring’:
/usr/include/postgresql/19/server/fmgr.h:249:43: error: expected expression before ‘)’ token
  249 |         pg_detoast_datum_packed((varlena *) DatumGetPointer(datum))